spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/git_project
    username: postgres
    password: 2c6U0XEdvJLK4XPDTEVb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      connection:
        isolation: 2
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
